//Write a method to find list of records a particular user has access 
//a.Input – user list 
//b.Output – list of records that user has READ/WRITE access 

//User Name 			List of records
//User1@user.com 			READ- {Record1,record2,record3}
						   //WRITE-{Record4,5,6)
//User2@user.com 			WRITE {Record1,record2,record3}
						   //READ -{Record4,5,6)



public class UserAcess
{
	public static void sharingRecordsForUser(list<User> ur)
    {
        
    }
}